SELECT * FROM supply_chain_data;
SELECT * FROM supply_chain_data LIMIT 10;
SELECT COUNT(*) FROM supply_chain_data;
DESCRIBE supply_chain_data;
SELECT COUNT(*) AS Total_Rows, COUNT(Price) AS Price_Rows FROM supply_chain_data;
SELECT * FROM supply_chain_data WHERE Product_Type IS NULL;
SELECT * FROM supply_chain_data WHERE SKU IS NULL;
SELECT SKU, COUNT(*) FROM supply_chain_data GROUP BY SKU HAVING COUNT(*) > 1;
SELECT DISTINCT Product_Type FROM supply_chain_data;
SELECT DISTINCT Customer_demographics FROM supply_chain_data;
SELECT DISTINCT Inspection_results FROM supply_chain_data;
SELECT DISTINCT Transportation_modes FROM supply_chain_data;
SELECT ROUND(MIN(Price),2) AS Min_Price, ROUND(MAX(Price),2) AS Max_Price, ROUND(AVG(Price),2) AS Avg_Price FROM supply_chain_data;
SELECT MIN(Rev_Gen), MAX(Rev_Gen), AVG(Rev_Gen) FROM supply_chain_data;
SELECT MIN(Defect_rates), MAX(Defect_rates), AVG(Defect_rates) FROM supply_chain_data;
SELECT MIN(Shipping_Costs), MAX(Shipping_Costs), AVG(Shipping_Costs) FROM supply_chain_data;
SELECT * FROM supply_chain_data WHERE Price < 0;
SELECT * FROM supply_chain_data WHERE stock_levels < 0;

SELECT COUNT(*) AS Total_Records FROM supply_chain_data;
SELECT COUNT(DISTINCT SKU) AS Total_Products FROM supply_chain_data;
SELECT COUNT(DISTINCT Supplier_name) AS Total_suppliers FROM supply_chain_data;
SELECT DISTINCT Supplier_Name FROM supply_chain_data;
SELECT ROUND(SUM(Rev_Gen),2) AS Total_Revenue FROM supply_chain_data;
SELECT Product_type, ROUND(SUM(Rev_Gen),2) AS Revenue FROM supply_chain_data GROUP BY Product_type ORDER BY Revenue DESC;
SELECT Product_type, ROUND(SUM(No_of_Products_sold),2) AS Products_Sold FROM supply_chain_data GROUP BY product_type ORDER BY Products_sold DESC;
SELECT Customer_demographics, ROUND(SUM(Rev_Gen),2) AS Revenue FROM supply_chain_data GROUP BY Customer_demographics ORDER BY Revenue DESC;
SELECT ROUND(AVG(Price),2) AS Average_Price FROM supply_chain_data;
SELECT ROUND(AVG(Stock_levels),2) AS Avg_Stock FROM supply_chain_data;
SELECT SKU, Product_type, Stock_levels FROM supply_chain_data ORDER BY Stock_levels DESC LIMIT 10;
SELECT SKU, Product_type, Stock_levels FROM supply_chain_data ORDER BY Stock_levels ASC LIMIT 10;
SELECT SKU, Product_Type, No_of_products_sold, Stock_levels FROM supply_chain_data ORDER BY No_of_products_sold DESC, Stock_levels ASC LIMIT 20;
SELECT Supplier_Name, ROUND(SUM(Rev_Gen),2) AS Revenue FROM supply_chain_data GROUP BY Supplier_Name ORDER BY Revenue DESC;
SELECT Supplier_name, ROUND(AVG(Manufacturing_costs),2) AS Avg_Manfacturing_Costs FROM supply_chain_data GROUP BY Supplier_Name ORDER BY Avg_Manfacturing_Costs DESC;
SELECT Supplier_Name, ROUND(AVG(Defect_rates),2) AS Avg_Defect_rates FROM supply_chain_data GROUP BY Supplier_name ORDER BY Avg_Defect_Rates DESC;
SELECT Supplier_Name, ROUND(AVG(Manufacturing_Lead_Time),2) AS Avg_Lead_Time FROM supply_chain_data GROUP BY Supplier_Name ORDER BY Avg_Lead_Time DESC;
SELECT Shipping_carriers, ROUND(AVG(Shipping_Costs),2) AS Avg_Shipping_Costs FROM supply_chain_data GROUP BY Shipping_Carriers ORDER BY Avg_Shipping_Costs DESC;
SELECT Shipping_carriers, ROUND(AVG(Shipping_Times),2) AS Avg_Shipping_Time FROM supply_chain_data GROUP BY Shipping_Carriers ORDER BY Avg_Shipping_Time DESC;
SELECT Transportation_Modes, ROUND(AVG(Shipping_Costs),2) AS avg_shipping_costs, ROUND(AVG(Shipping_Times),2) AS Avg_Shipping_Time FROM supply_chain_data GROUP BY Transportation_Modes;
SELECT Routes, ROUND(AVG(Shipping_Costs),2) AS Avg_Shipping_Costs FROM supply_chain_data GROUP BY Routes ORDER BY avg_shipping_costs DESC;
SELECT Product_Type, ROUND(AVG(Manufacturing_Costs),2) AS Avg_Manufacturing_Costs FROM supply_chain_data GROUP BY Product_type ORDER BY Avg_Manufacturing_Costs DESC;
SELECT Product_Type, SUM(Production_Volumes) AS total_production FROM supply_chain_data GROUP BY product_type ORDER BY total_production;
SELECT Inspection_results, COUNT(*) AS Total FROM supply_chain_data GROUP BY Inspection_results;
SELECT Product_type, ROUND(AVG(Defect_Rates),2) AS Avg_Defect_Rates FROM supply_chain_data GROUP BY Product_type ORDER BY Avg_Defect_Rates DESC;
SELECT Transportation_Modes, ROUND(AVG(Defect_Rates),2) AS Avg_Defect_Rates FROM supply_chain_data GROUP BY Transportation_Modes;
